/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:c8142e66-b2fe-446a-b0ed-cbbbcd1a2720",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_yWHK6Djnu",
  aws_user_pools_web_client_id: "bl8ri3tsprsvg6tclka53ko3m",
  oauth: {},
  aws_content_delivery_bucket:
    "beverlyhillsfrontend-20200725200339-hostingbucket-dev",
  aws_content_delivery_bucket_region: "us-east-1",
  aws_content_delivery_url:
    "http://beverlyhillsfrontend-20200725200339-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
  aws_appsync_graphqlEndpoint:
    "https://u7el2x36i5glpine6rs5fxqwpa.appsync-api.us-east-1.amazonaws.com/graphql",
  aws_appsync_region: "us-east-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-z2titrwl6bb2zggk2ol7vsvafy",
};

export default awsmobile;
